version: 2
jobs:
  build:
    docker:
      - image: node:10
    working_directory: ~/uikit-site
    steps:
      - run:
          name: Update Environment
          command: apt-get update && apt-get -y install rsync
      - checkout
      - restore_cache:
          key: yarn-{{ checksum "yarn.lock" }}
      - run:
          name: Dependencies
          command: |
            yarn install --pure-lockfile --cache-folder ~/.yarn
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.yarn
            - ./node_modules
      - run:
          name: Compile
          command: |
            yarn compile
      - run:
          name: Replace Build Number
          command: |
            sed -i -- "s/{{BUILD}}/$CIRCLE_BUILD_NUM/g" app/main.min.js
            sed -i -- "s/{{BUILD}}/$CIRCLE_BUILD_NUM/g" docs/app/main.min.js
            sed -i -- "s/{{BUILD}}/$CIRCLE_BUILD_NUM/g" docs/index.html
            sed -i -- "s/{{BUILD}}/$CIRCLE_BUILD_NUM/g" index.html
      - run:
          name: Transfer Files
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ];then
              rsync -avze "ssh -o StrictHostKeyChecking=no" --exclude-from ".circleci/exclude.txt" --copy-links --checksum --delete . $UIKIT_SERVER
            else
              echo "Skipping deploy on branch ${CIRCLE_BRANCH}";
            fi
